import { z } from 'zod';

// ── Submit ZKP proof ───────────────────────────────────────────
export const submitProofSchema = z.object({
  disasterEventId: z
    .string({ required_error: 'disasterEventId is required' })
    .uuid('Invalid disasterEventId'),
  warehouseId: z
    .string({ required_error: 'warehouseId is required' })
    .uuid('Invalid warehouseId'),
  // The proof object generated by snarkjs on the client side
  proof: z.object({
    pi_a: z.array(z.string()),
    pi_b: z.array(z.array(z.string())),
    pi_c: z.array(z.string()),
    protocol: z.string(),
    curve: z.string(),
  }, { required_error: 'proof is required' }),
  // Public signals: [threshold, warehouseCommitment, valid]
  publicSignals: z
    .array(z.string(), { required_error: 'publicSignals is required' })
    .length(3, 'publicSignals must have exactly 3 elements'),
});

// ── Generate proof params (for testing via API) ────────────────
export const generateProofSchema = z.object({
  warehouseId: z
    .string({ required_error: 'warehouseId is required' })
    .uuid('Invalid warehouseId'),
  disasterEventId: z
    .string({ required_error: 'disasterEventId is required' })
    .uuid('Invalid disasterEventId'),
  availableCapacity: z
    .number({ required_error: 'availableCapacity is required' })
    .nonnegative('availableCapacity must be >= 0'),
  threshold: z
    .number({ required_error: 'threshold is required' })
    .positive('threshold must be > 0'),
});

export type SubmitProofInput    = z.infer<typeof submitProofSchema>;
export type GenerateProofInput  = z.infer<typeof generateProofSchema>;