from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, model_validator


class NegotiationAction(str, Enum):
    ACCEPT = "accept"
    COUNTER_OFFER = "counter_offer"
    REJECT = "reject"


class NegotiationDecision(BaseModel):
    """
    Strict structured decision generated by an agent.
    Every output must include all five properties.
    """

    action: NegotiationAction

    price: Optional[float] = Field(
        ...,
        ge=0,
        description=(
            "Required field. Use a numeric price per kilogram "
            "for accept and counter_offer. Use null for reject."
        ),
    )

    reason: str = Field(
        ...,
        min_length=3,
        max_length=300,
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=1,
    )

    market_alignment: Literal[
        "below_market",
        "near_market",
        "above_market",
    ] = Field(...)

    @model_validator(mode="after")
    def validate_action_price(self):
        if (
            self.action
            in {
                NegotiationAction.ACCEPT,
                NegotiationAction.COUNTER_OFFER,
            }
            and self.price is None
        ):
            raise ValueError(
                "Price is required for accept or counter_offer."
            )

        if (
            self.action == NegotiationAction.REJECT
            and self.price is not None
        ):
            raise ValueError(
                "Price must be null for reject."
            )

        return self


class NegotiationHistoryItem(BaseModel):
    round_number: int = Field(ge=0)
    agent: str
    action: NegotiationAction
    price: Optional[float] = Field(default=None, ge=0)
    reason: str


class FarmerAgentInput(BaseModel):
    negotiation_id: str

    round_number: int = Field(
        ge=1,
    )

    max_rounds: int = Field(
        ge=1,
        le=20,
    )

    paddy_type: str

    quantity_kg: float = Field(
        gt=0,
    )

    district: str

    farmer_expected_price: float = Field(
        gt=0,
    )

    farmer_minimum_price: float = Field(
        gt=0,
    )

    miller_current_offer: float = Field(
        gt=0,
    )

    fl_reference_price: float = Field(
        gt=0,
    )

    matching_score: float = Field(
        ge=0,
        le=100,
    )

    history: list[NegotiationHistoryItem] = Field(
        default_factory=list,
    )

    @model_validator(mode="after")
    def validate_farmer_prices(self):
        if (
            self.farmer_minimum_price
            > self.farmer_expected_price
        ):
            raise ValueError(
                "Farmer minimum price cannot be greater "
                "than farmer expected price."
            )

        return self


class MillerAgentInput(BaseModel):
    negotiation_id: str

    round_number: int = Field(
        ge=1,
    )

    max_rounds: int = Field(
        ge=1,
        le=20,
    )

    paddy_type: str

    requested_quantity_kg: float = Field(
        gt=0,
    )

    available_quantity_kg: float = Field(
        gt=0,
    )

    district: str

    miller_opening_price: float = Field(
        gt=0,
    )

    miller_maximum_price: float = Field(
        gt=0,
    )

    farmer_current_offer: float = Field(
        gt=0,
    )

    fl_reference_price: float = Field(
        gt=0,
    )

    matching_score: float = Field(
        ge=0,
        le=100,
    )

    history: list[NegotiationHistoryItem] = Field(
        default_factory=list,
    )

    @model_validator(mode="after")
    def validate_miller_prices(self):
        if (
            self.miller_opening_price
            > self.miller_maximum_price
        ):
            raise ValueError(
                "Miller opening price cannot be greater "
                "than miller maximum price."
            )

        return self
    

class NegotiationStatus(str, Enum):
    AGREED = "agreed"
    REJECTED_BY_FARMER = "rejected_by_farmer"
    REJECTED_BY_MILLER = "rejected_by_miller"
    MAX_ROUNDS_REACHED = "max_rounds_reached"
    VALIDATION_FAILED = "validation_failed"


class NegotiationRequest(BaseModel):
    negotiation_id: str = Field(
        min_length=1,
        max_length=100,
    )

    paddy_type: str = Field(
        min_length=1,
        max_length=100,
    )

    district: str = Field(
        min_length=1,
        max_length=100,
    )

    quantity_kg: float = Field(
        gt=0,
    )

    farmer_expected_price: float = Field(
        gt=0,
    )

    farmer_minimum_price: float = Field(
        gt=0,
    )

    miller_opening_price: float = Field(
        gt=0,
    )

    miller_maximum_price: float = Field(
        gt=0,
    )

    fl_reference_price: float = Field(
        gt=0,
    )

    matching_score: float = Field(
        ge=0,
        le=100,
    )

    max_rounds: int = Field(
        default=6,
        ge=1,
        le=20,
    )

    @model_validator(mode="after")
    def validate_private_price_boundaries(self):
        if (
            self.farmer_minimum_price
            > self.farmer_expected_price
        ):
            raise ValueError(
                "Farmer minimum price cannot exceed "
                "farmer expected price."
            )

        if (
            self.miller_opening_price
            > self.miller_maximum_price
        ):
            raise ValueError(
                "Miller opening price cannot exceed "
                "miller maximum price."
            )

        return self


class NegotiationResult(BaseModel):
    negotiation_id: str
    status: NegotiationStatus

    agreed_price: Optional[float] = Field(
        default=None,
        ge=0,
    )

    rounds_completed: int = Field(
        ge=0,
    )

    final_reason: str

    fl_reference_price: float = Field(
        gt=0,
    )

    price_difference_from_reference: Optional[float] = None

    fairness_score: Optional[float] = Field(
        default=None,
        ge=0,
        le=100,
    )

    history: list[NegotiationHistoryItem] = Field(
        default_factory=list,
    )