const mongoose = require("mongoose");

const recommendationSchema = new mongoose.Schema(
  {
    english: {
      type: String,
      default: ""
    },
    sinhala: {
      type: String,
      default: ""
    }
  },
  { _id: false }
);

const harvestSchema = new mongoose.Schema(
  {
    farmerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Farmer",
      required: true
    },

    paddyType: {
      type: String,
      required: true,
      trim: true
    },

    season: {
      type: String,
      required: true,
      trim: true,
      lowercase: true
    },

    quantity: {
      type: Number,
      required: true,
      min: 1
    },

    // Price manually entered by the farmer
    expectedPrice: {
      type: Number,
      required: true,
      min: 0
    },

    // Price generated by the Federated Learning model
    aiPredictedPrice: {
      type: Number,
      required: true,
      min: 0
    },

    // Expected price minus AI predicted price
    priceDifference: {
      type: Number,
      default: 0
    },

    // COMPETITIVE, SLIGHTLY_HIGH, HIGH, VERY_HIGH, BELOW_MARKET
    priceLevel: {
      type: String,
      default: "COMPETITIVE"
    },

    // Overall market attractiveness from 0 to 100
    harvestScore: {
      type: Number,
      min: 0,
      max: 100,
      default: 0
    },

    // HIGH_DEMAND, MODERATE_DEMAND, LOW_DEMAND
    marketStatus: {
      type: String,
      default: "LOW_DEMAND"
    },

    recommendedAction: {
      type: String,
      default: "REVIEW_MARKET"
    },

    recommendation: {
      type: recommendationSchema,
      default: () => ({
        english: "",
        sinhala: ""
      })
    },

    status: {
      type: String,
      enum: ["available", "matched", "sold", "cancelled"],
      default: "available"
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model("Harvest", harvestSchema);